
# The name given to the Redis service (lowercase alphanumeric only).
redis:
    # The type of your service (redis), which uses the format
    # 'type:version'. Be sure to consult the Redis documentation
    # (https://docs.platform.sh/add-services/redis.html#supported-versions)
    # when choosing a version. If you specify a version number which is not available,
    # the CLI will return an error.
    type: redis:7.2

# The name given to the Solr service (lowercase alphanumeric only).
solr:
    # The type of your service (solr), which uses the format
    # 'type:version'. Be sure to consult the Solr documentation
    # (https://docs.platform.sh/add-services/solr.html#supported-versions)
    # when choosing a version. If you specify a version number which is not available,
    # the CLI will return an error.
    type: solr:9.2
    # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
    disk: 256
